= Guía para usar contenedores de Docker con interfaz gráfica

.Métodos posibles:
* Enviar X11 a través de SSH
* Usar x11vnc

## Enviar X11 a través de SSH

Necesitamos asegurarnos de que tenemos dos opciones en el archivo de configuración de sshd. Este archivo casi siempre se encuentra en /etc/ssh/sshd_config. Es recomendable hacer una copia del archivo original con cp antes de modificarlo. Luego, podemos imponer las opciones con cualquier editor de texto.

.En la consola del host, ejecutamos:

```bash
$ sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.original
$ sudo nano /etc/ssh/sshd_config
```

.Tenemos que modificar las siguientes líneas:

```
X11Forwarding yes
X11UseLocalhost no
```

Tambíen necesitamos abrir el puerto de las X en la interfaz virtual de Docker. Por defecto, el servidor X del host escucha solo en lo. La mejor opción es permitir solo conexiones locales desde los puertos de Docker con xhost:

```bash
$ sudo xhost +local:docker
```

.Otra opción es permitir conexiones desde cualquier IP, pero esto es menos seguro:
```bash
$ sudo xhost +
```

.Es posible que necesitemos reiniciar el servicio sshd:

```bash
$ sudo service sshd restart
```

.Creamos el siguiente Dockerfile:

```Dockerfile
FROM ubuntu
RUN apt-get update && apt-get install -qqy x11-apps
CMD xeyes
```

.Construimos la imagen:

```bash
$ docker build -t sample:latest .
```

.Ejecutamos el contenedor:

```bash
$ docker run --rm -it --net=host --env DISPLAY=$DISPLAY sample:latest
```

### Problemas que pueden surgir
Cuando el contenedor se está ejecutando, necesita acceder al archivo .Xauthority para conectarse al servidor. Este archivo está relacionado con xhost y es sensible al nombre del host. Podemos dar a los contenedores diferentes nombres de host en Docker y encontrarnos con errores.

.La primera solución es montar el archivo .Xauthority y el socket X11 en el contenedor:

```bash
$ docker run --rm -it --net=host --env DISPLAY=$DISPLAY --volume $HOME/.Xauthority:/root/.Xauthority --volume /tmp/.X11-unix:/tmp/.X11-unix sample:latest
```

Por defecto, el usuario del contenedor tiene el mismo UID que el usuario del host. Cuando ejecutamos la aplicación GUI en el contenedor, comprueba si hay una cookie en el archivo .Xauthority que coincida con el nombre y $DISPLAY del host. Una vez encontrado, el cliente pasa la solicitud a través del socket /tmp/.X11-unix montado en el contenedor.

.La segunda solución es usar el mismo nombre de host para el contenedor y el host. Esto se puede hacer con la opción --hostname:

```bash
$ docker run --rm -it --net=host --env DISPLAY=$DISPLAY --hostname $HOSTNAME sample:latest
```

.La tercera solución es usar .Xauthority para poder tener un nombre usuario diferente:
Es posible que tengamos errores si hay diferentes usuarios creando y usando el contenedor. Aún podemos solucionar esto escribiendo el archivo .Xauthority para que el nombre de host no importe al verificar la entrada de la cookie.

.Para hacer esto, necesitamos instalar xauth en el host y en el contenedor. Luego, podemos ejecutar el siguiente comando en el host:

```bash
$ touch /tmp/.docker.xauth
$ xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f /tmp/.docker.xauth nmerge - 
```

.Luego, podemos ejecutar el contenedor con el siguiente comando:

```bash
$ sudo docker run --rm -it --net=host --volume /tmp/.docker.xauth:/tmp/.docker.xauth --volume /tmp/.X11-unix:/tmp/.X11-unix --env DISPLAY=$DISPLAY --env XAUTHORITY=/tmp/.docker.xauth ssh_image_tag_1 
```

## Usar x11vnc

Otra forma de ejecutar aplicaciones GUI en contenedores es usar x11vnc. Este método es más fácil de configurar y más seguro que el anterior. Sin embargo, es más lento y no es compatible con todas las aplicaciones.

.Creamos el siguiente Dockerfile:

```Dockerfile
FROM ubuntu
RUN apt-get update && apt-get install -qqy x11-apps x11vnc xvfb
RUN mkdir ~/.vnc 
RUN x11vnc -storepasswd 1234 ~/.vnc/passwd 
CMD xeyes
```

.Construimos la imagen:

```bash
$ docker build -t sample:latest .
```

.Ejecutamos el contenedor (es posible que necesitemos permisos de root):

```bash
$ docker run --rm -p 5900:5900 --env HOME=/ ssh_image_tag_2 x11vnc -create
```

.Ahora podemos conectarnos al contenedor con cualquier cliente VNC. El puerto 5900 está expuesto en el host, por lo que podemos usar cualquier cliente VNC en el host para conectarnos al contenedor.
