version: "3.7"
services:
 web:
   image: nginx:latest
   ports:
     - "8081:80"
   deploy:
     replicas: 5
     restart_policy:
       condition: on-failure
 db:
   image: postgres:9.4
   volumes:
     - db-data:/var/lib/postgresql/data
volumes:
   db-data: